language: cpp
addons:
  apt:
    packages:
    - cmake
    sources:
    - kalakris-cmake
matrix:
  include:
  - os: osx
    compiler: clang
    env: ITK_VERSION=v4.13.1
  - os: linux
    compiler: gcc
    env: ITK_VERSION=v4.13.1
cache:
- directories:
  - $HOME/itk-v4.13.1-build
  - $HOME/itk-v4.13.1
before_script:
- export NUM_THREADS=4
- export ITK_SOURCE_DIR=$HOME/itk-${ITK_VERSION}
- export ITK_BUILD_DIR=${ITK_SOURCE_DIR}-build
- if ! test -e ${ITK_SOURCE_DIR}/CMakeLists.txt; then rm -fr $ITK_SOURCE_DIR; fi
- if ! test -d ${ITK_SOURCE_DIR}; then git clone --branch ${ITK_VERSION} https://github.com/InsightSoftwareConsortium/ITK.git
  ${ITK_SOURCE_DIR}; fi
- if ! test -d ${ITK_BUILD_DIR}; then mkdir ${ITK_BUILD_DIR}; fi
- cd ${ITK_BUILD_DIR}
- cmake ${ITK_SOURCE_DIR} -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=OFF -DBUILD_TESTING=OFF
  -DModule_ITKReview=ON
- make --jobs=$NUM_THREADS --keep-going
- cd -
- cd ..
- mkdir build
- cd build
- cmake ../PETPVC -DCMAKE_BUILD_TYPE=Release
script: cmake --build . && ctest && cpack
deploy:
  - provider: releases
    api_key:
      secure: YSxN8Qk4LeYNY7nJduF1Gw1QdpoEK7eJbTwtLLiHpRKPKOpfYR3l4PrWDFwCcye6xX+uDJPJ/yLqtpMrP/1KSDEg3nIpAGjYTh4Y1qHjoJthiRga5G55/iRGPSxkaDC5his0zEfjNcUeULgQMc+8QE0gWm+PDbKlunOIv/h8frrOoNGXBBXejni/WysMEgX9JQNqyjJ5ROJqSiCi4f3+ubPe+oRFPdJDv9dKIEwdQPjwl55NPVVG689zJqRtQP7Vf3XBnY7OGd5cHARPqjUWAPOVzS/up1RPFF6kv5UEw5IxQg++rcn3Hpw7aoUKEo1UZop2eHUMVnuwKgteEhyouGgzWGITM7pOA4RqsjfTTBxXOJJav7c7b+FjYwjL2wsRICb1nMc553vLYeZ03fm3+6hwLUVqtDWdak5cKzjK9e5NGdjVkEau5iN+k0IrEogVhj7RvCP7P0M6iRp7W5XDxYCPfpTgZzTUzoJJYE6frHxrKXFBbHkKqPnEUWXsUAq7NOj6U8V9rWphbqIFUzjnHzxZShsmU1uSlsnOExAOIjBjYIWlntX1PVos2xyrbE/mhA7Ac/Zl3O/mTy+LoVdR4LW+c/M0cIldS5hvvOOa2k4HYwbqQN60dqgzrdJMfnVJ8GYU5RwGfWQPjB1jZIvQcNpXVzLp1XxzPY4WfXpTRhM=
    file: "*.tar.gz"
    file_glob: true
    draft: true
    on:
      tags: true
      all_branches: true
