language: cpp
compiler:
  - gcc
  - clang
before_script:
  - sudo apt-get install libinsighttoolkit4-dev
  -  cd ..
  - mkdir build
  - cd build
  - cmake ../PETPVC
  script: cmake --build . && ctest
