language: cpp

compiler:
- gcc
- clang

matrix:
  include:
    - os: osx
      compiler: clang
      env: ITK_VERSION=v4.10.0
    - os: linux
      compiler: gcc
      env: ITK_VERSION=v4.10.0
   
cache:
  - directories:
    - $HOME/itk-v4.10.0-build
    - $HOME/itk-v4.10.0

before_script:
  - export NUM_THREADS=4
  - export ITK_SOURCE_DIR=$HOME/itk-${ITK_VERSION}
  - export ITK_BUILD_DIR=${ITK_SOURCE_DIR}-build
  - git clone --branch ${ITK_VERSION} git://itk.org/ITK.git ${ITK_SOURCE_DIR}
  - mkdir ${ITK_BUILD_DIR}
  - cd ${ITK_BUILD_DIR}
  - cmake ${ITK_SOURCE_DIR}
    -DCMAKE_BUILD_TYPE=Release
    -DBUILD_EXAMPLES=OFF
    -DBUILD_TESTING=OFF
    -DModule_ITKReview=ON
  - make --jobs=$NUM_THREADS --keep-going
  - cd -
  -  cd ..
  - mkdir build
  - cd build
  - cmake ../PETPVC
  
script: cmake --build . && ctest
